"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const gen_monster_1 = __importDefault(require("./routes/gen-monster"));
const gen_equipment_1 = __importDefault(require("./routes/gen-equipment"));
const gen_dungeon_1 = __importDefault(require("./routes/gen-dungeon"));
const gen_character_1 = __importDefault(require("./routes/gen-character"));
const login_1 = __importDefault(require("./routes/login"));
const mainmenu_1 = __importDefault(require("./routes/mainmenu"));
const AIRouter_1 = __importDefault(require("./routes/AIRouter"));
const app = (0, express_1.default)();
const port = 3000;
app.set('view engine', 'ejs');
app.use(express_1.default.static(__dirname + '/public'));
app.use(express_1.default.json());
app.use('/', login_1.default);
app.use('/main', mainmenu_1.default);
app.use('/monster', gen_monster_1.default);
app.use('/equipment', gen_equipment_1.default);
app.use('/dungeon', gen_dungeon_1.default);
app.use('/character', gen_character_1.default);
app.use('/ai', AIRouter_1.default);
app.listen(port, () => console.log(`Express app running on port ${port}!`));
